name: Test
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install libsqlite3-dev
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Bundle install
      run: bundle exec rake test
